language: php

# Versiones de PHP contra las cuales quieres probar tu aplicación
php:
  - 7.2
  - 7.4
  - 8.1

# Instala las dependencias necesarias para el proyecto
before_script:
  - composer install
